name: gs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - configargparse=1.7
  - cudatoolkit=11.6
  - imageio=2.31.2
  - imageio-ffmpeg=0.4.9
  - lpips=0.1.4
  - plyfile=0.8.1
  - pip=22.3.1
  - python=3.7.13
  - pytorch=1.12.1
  - scipy=1.7.3
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - pip:
    - submodules/simple-knn